In [1]:
import numpy as np

In [2]:
# Creating an array
a = np.array([2, 4, 6, 8, 10])
print(a)

[ 2  4  6  8 10]


In [21]:
# Another way of creating array using arange()
a = np.arange(1, 11)
print(a)
print(a.dtype)
print(a.dtype.itemsize) # dtyoe objects also tell us the size of the data type in bytes using the itemsize property

print(type(a))  # returns numpu.ndarray
print(a.shape)


[ 1  2  3  4  5  6  7  8  9 10]
int64
8
<class 'numpy.ndarray'>
(10,)


zero() : The zeros() function creates an array for a given dimension with all zeros.

ones(): The ones () function creates an array for a given dimension with all ones.

fulls(): The full() function generates an array with constant values.

eyes() : The eye() function creates an identity matrix.

random(): The random() function creates an array with any given dimension



In [7]:
# Create an array of all zeros
p = np.zeros((3, 3))
print(p)

# Create an array of all ones
q = np.ones((2, 2))
print(q)

# Create a constant array
r = np.full((2, 2), 4)
print(r)

# Create a 2 x 2 identity matrix
s = np.eye(4)
print(s)

# Create an array filled with random values
t = np.random.random((3, 3))
print(t)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[4 4]
 [4 4]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.86931232 0.20554375 0.23637265]
 [0.49585567 0.23504393 0.76663694]
 [0.75388283 0.85220823 0.16435633]]


Selecting array elements

In [8]:
a = np.array([[5, 6], [7, 8]])
print(a)


[[5 6]
 [7 8]]


In [9]:
print(a[0, 0])
print(a[0, 1])
print(a[1,0])
print(a[1,1])

5
6
7
8


Manipulating array shapes

functions of numpy, such ad reshape(), flatten(), ravel(), transpose(), and resize()

reshape() -- will change the shape of the array

In [10]:
arr = np.arange(12)
print(arr)

new_arr = arr.reshape(4, 3)
print(new_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
new_arr2  = arr.reshape(3, 4)
print(new_arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


The main difference is that flatten() returns the actual array while ravel() returns the reference of the original array. The ravel() function is faster than the flatten() function because it does not occupy extra memory

In [16]:
# to convert or transform an n-dimensional array into one-dimensional array

arr = np.arange(1, 10).reshape(3, 3)
print(arr)
print(arr.flatten())
print(arr.ravel())
print(arr.transpose())




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
arr.resize(1, 9)
print(arr)


[[1 2 3 4 5 6 7 8 9]]


The stacking of NumPy arrays

Horizontal stacking: The same dimensional arrays are joined along with a horizontal axis using the hstack() and concatenate()

In [24]:
arr1 = np.arange(1, 10).reshape(3, 3)
print(arr1)

arr2 = 2 * arr1
print(arr2)

# Horizpntal stacking
arr3 = np.hstack((arr1, arr2))
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


In [27]:
# to achieve the same horizontal stacking with concatenate with axis parameter value 1:
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


Vertical stacking: the same dimensional arrays are joined along with a vertical axis using the vstack() and concatenate() functions

In [29]:
arr5 = np.vstack((arr1, arr2))
print(arr5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [31]:
arr6 = np.concatenate((arr1, arr2), axis=0)
print(arr6)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Depth stacking: in depth stacking, the same dimensional arrays are joined along wwith a third axis(depth) using the dstack() function

In [32]:
arra7 = np.dstack((arr1, arr2))
print(arra7)

[[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[ 4  8]
  [ 5 10]
  [ 6 12]]

 [[ 7 14]
  [ 8 16]
  [ 9 18]]]


Column stacking: Column stacking stacks multiple sequence one-dimensional arrays as columns into a single two-dimensional array

In [33]:
arr3 = np.arange(4, 7)
print(arr3)

arr4 = arr3 *  2
print(arr4)

# Create column stack
arr_col_stack = np.column_stack((arr3, arr4))
print(arr_col_stack)

[4 5 6]
[ 8 10 12]
[[ 4  8]
 [ 5 10]
 [ 6 12]]


Row stacking - stacks multiple sequence one-dimensional arrays as rows into a single two-dimensional arrays


In [35]:
arr_row_stack = np.row_stack((arr1, arr2))
print(arr_row_stack)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


/var/folders/mj/mwfbn2ps169f3kp750c4p5tc0000gn/T/ipykernel_2874/631339741.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  arr_row_stack = np.row_stack((arr1, arr2))


Partitioning NumPy aarays

Horizontal spitting : the given array is divided into N equal sub-arrays along the horizontal axis using the hsplit() function

In [38]:
# Create an array
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

# horizontal splitting
arr_hor_spilt = np.hsplit(arr, 3)
print(arr_hor_spilt)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


Vertical splitting : In vertical split, the given array is divided into N equal sub-arrays along the vertical axis using the vspilt() and the split() functions. the spilt function with axis=0 performs the same operation as the vsplit() function

In [41]:
# vertical spilt
arr_ver_split = np.vsplit(arr, 3)
print(arr_ver_split)

# split with axis=0
arr_split = np.split(arr, 3)
print(arr_split)

# split with axis=1
arr_split2 = np.split(arr, 3, axis=1)
print(arr_split2)




[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


Changing the data type pf NumPy arrays

In [42]:
# Create an array
arr = np.arange(1, 10).reshape(3, 3)
print("Integer Array:", arr)

Integer Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
# Change datatype of array
arr = arr.astype(float)
print("Float Array:", arr)

# Check new data type pf array
print("Changed DataType:", arr.dtype)

Float Array: [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Changed DataType: float64


In [44]:
arr = np.arange(1, 10)

# Convert Numpy array to Python List
list = arr.tolist()
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


Creating numPy views and copies

In [45]:
arr = np.arange(1, 5).reshape(2, 2)
print(arr)



[[1 2]
 [3 4]]


In [46]:
# Create no copy nly assignment
arr_no_copy = arr

# Create Deep Copy
arr_copy = arr.copy()

# Create shallow copy using view
arr_view = arr.view()

print("Original Array:", id(arr))
print("Assignment:", id(arr_no_copy))
print("Deep Copy:", id(arr_copy))
print("Shallow Copy(View):", id(arr_view))

Original Array: 4832699632
Assignment: 4832699632
Deep Copy: 4832988208
Shallow Copy(View): 4832699344


In [47]:
# Update the values of original array
arr[1] = [99, 89]

# Check values of array view
print("View Array:\n", arr_view)
print("Copied Array:\n", arr_copy)



View Array:
 [[ 1  2]
 [99 89]]
Copied Array:
 [[1 2]
 [3 4]]


Slicing NumPy arrays

In [48]:
arr = np.arange(0, 10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [49]:
print(arr[:3])

[0 1 2]


In [51]:
print(arr[3:])

[3 4 5 6 7 8 9]


In [52]:
print(arr[-3:])

[7 8 9]


In [53]:
print(arr[2:7:2])
# The start, stop and the step index are 2, 7 and 2


[2 4 6]


Boolean and fancy indexing : Indexing techniques help us to select and filter elements from a NumPy array. This indexing returns elements that have a true value for the Boolean expression


In [54]:
arr =np.arange(21, 41, 2)
print("Original Array:\n", arr)

# Boolean Indexing
print("After Boolean Condition:", arr[arr>30])

Original Array:
 [21 23 25 27 29 31 33 35 37 39]
After Boolean Condition: [31 33 35 37 39]


Fancing Indexing is a special type of indexing in which elements of an array are selected by an array of indices. This means we pass the array of indices in brackets. Fancy indexing also supports multi-dimensional arrays. Ths will help us to easily select and modify a complex multi-dimensional set of arrays

In [56]:
arr = np.arange(1, 21).reshape(5, 4)
print("Original Array:\n", arr)

# Selecting 2nd and 3rd row
indices = [0, 1]
print("Selected Ist and 2nd Row:\n", arr[indices])


# Selecting 3rd and 4th row
indices = [2, 3]
print("Selected 3rd and 4th Row:\n", arr[indices])

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
Selected Ist and 2nd Row:
 [[1 2 3 4]
 [5 6 7 8]]
Selected 3rd and 4th Row:
 [[ 9 10 11 12]
 [13 14 15 16]]


In [58]:
row = np.array([1, 2])
col = np.array([2, 3])

print("Selected Sub-Array: ", arr[row,col])

Selected Sub-Array:  [ 7 12]


Broadcasting arrays: python lists do not support direct vectorizing arithmetic operations. NumPy offers a faster vectorized array operation compared to Python list loop-based operations. Broadcasting functionality checks a set of rules for applying binary functions, such as addition, substraction, multiplication on different shapes of an array

In [59]:
arr1 = np.arange(1, 5).reshape(2, 2)
print(arr1)

[[1 2]
 [3 4]]


In [60]:
arr2 = np.arange(5,9).reshape(2, 2)
print(arr2)

[[5 6]
 [7 8]]


In [61]:
# Add two matrices

print(arr1 + arr2)

[[ 6  8]
 [10 12]]


In [62]:
# Multiply two matrices
print(arr1 * arr2)

[[ 5 12]
 [21 32]]


In [63]:
# Add a scaler value
print(arr1 + 3)

[[4 5]
 [6 7]]


In [64]:
#Multiply with a scalar value
print(arr1 * 3)

[[ 3  6]
 [ 9 12]]
